services:  
  terminal.reverse-proxy:
    image: nginx:latest
    volumes:
      - ./config/reverse-proxy:/etc/nginx/conf.d/:ro
    ports:
      - 8080:80
    depends_on: [terminal.backend, terminal.frontend]

  terminal.backend:
    build:
      context: ./Backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - terminal.postgres
  
  terminal.frontend:
    build:
      context: ./Frontend
    volumes:
      - ./config/frontend:/etc/nginx/conf.d/:ro
    depends_on:
      - terminal.backend

  terminal.postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - ~/terminal-data:/var/lib/postgresql/data
