services:  
  terminal.backend:
    build:
      context: ./Backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - terminal.postgres
    ports:
      - 8080:8080

  terminal.frontend:
    build:
      context: ./Frontend
    volumes:
      - ./config/frontend:/etc/nginx/conf.d/:ro
    depends_on:
      - terminal.backend
    ports:
      - 8081:80

  terminal.postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - ~/terminal-data:/var/lib/postgresql/data
