services:
  terminal.poc.reverse-proxy:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/nginx:/etc/nginx/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - /etc/letsencrypt/:/etc/ssl/:ro
    depends_on: [terminal.poc.backend, terminal.poc.frontend]

  terminal.poc.backend:
    build:
      context: .
      dockerfile: Dockerfile

  terminal.poc.frontend:
    build:
      context: client
      dockerfile: Dockerfile