services:
    dev:
        image: terminal-web-dev
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "4201:4200"
        volumes:
            - ./src:/app/src

    prod:
        image: terminal-web
        build:
            context: .
            dockerfile: Dockerfile.production
        ports:
            - "80:80"
