name: terminal-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Setup Node
      uses: actions/setup-node@v3
      with: 
        node-version: 18
    - name: Setup Angular
      run: npm install -g @angular/cli
    - name: Restore .NET dependencies
      run: dotnet restore Backend/Terminal.Backend.sln
    - name: Build .NET
      run: dotnet build --no-restore Backend/Terminal.Backend.sln
    - name: Publish .NET
      run: dotnet publish -c Release -o terminal-backend
      working-directory: ./Backend
    - name: Upload .NET artifacts
      uses: actions/upload-artifacts@v3
      with:
        name: terminal-backend
        path: ./Backend/terminal-backend
    - name: Restore Angular dependencies
      run: npm ci
      working-directory: ./Frontend
    - name: Build Angular
      run: ng b -c production
      working-directory: ./Frontend
    - name: Upload Angular artifacts
      uses: actions/upload-artifacts@v3
      with:
        name: terminal-frontend
        path: ./Frontend/dist
    
  test:
    runs-on: self-hosted
    needs: build
    
    steps:
    - name: Test .NET
      run: dotnet test --no-build --verbosity normal
      working-directory: ./Backend
#     - name: Test Angular
#       run: ng test
      
  deploy:
    runs-on: self-hosted
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - run: cd ../
      - run: docker compose up --build -d
